export const menugenreDB = [
  { genre: 'Бизнес-книги', amount: 14, id: '/books/business' },
  { genre: 'Детективы', amount: 8, id: '/books/detective' },
  { genre: 'Детские книги', amount: 14, id: '/books/children' },
  { genre: 'Зарубежная литература', amount: 2, id: '/books/foreign' },
  { genre: 'История', amount: 5, id: '/books/history' },
  { genre: 'Классическая литература', amount: 12, id: '/books/classic' },
  { genre: 'Компьютерная литература', amount: 54, id: '/books/computer' },
  { genre: 'Культура и искусство', amount: 5, id: '/books/culture' },
  { genre: 'Наука и образование', amount: 2, id: '/books/science' },
  { genre: 'Публицистическая литература', amount: 0, id: '/books/journalistic' },
  { genre: 'Справочники', amount: 10, id: '/books/reference' },
  { genre: 'Фантастика', amount: 12, id: '/books/fantasy' },
  { genre: 'Юмористическая литература', amount: 8, id: '/books/comedy' },
];
